### ISSUE TITLE
tosu cannot working on the local area network.

### ISSUE THREAD

**Issue by wanjiaXG** [tosuapp/tosu#313]
I'm not sure if this bug was not included in the implementation plan, I just discovered it. Due to my use of a computer within the local area network for streaming, tsou cannot function properly like gosumemory.

![Image](https://github.com/user-attachments/assets/a917d5c7-f64c-4ec4-aea7-33449853a906)

Config:
```# The config implies a set of key-values to enable/disable tosu functionality
# Below you can see that there is EVERY_THE_FUNCTION=true/false,
# true = on
# false = off

# Turns PP counting on/off. Very useful for tournament client, when you only care about scoring and map stats for example
CALCULATE_PP=true
# Enables/disables reading K1/K2/M1/M2 keys on the keyboard
ENABLE_KEY_OVERLAY=true
ENABLE_AUTOUPDATE=true

ALLOWED_IPS=192.168.6.100,192.168.6.200,127.0.0.1,localhost,absolute

# Reference: 1 second = 1000 milliseconds
# Once in what value, the programme should read the game values (in milliseconds)
POLL_RATE=100
# Once per value, the programme should read the values of keys K1/K2/M1/M2 (in milliseconds)
PRECISE_DATA_POLL_RATE=10

# Shows !mp commands (messages starting with '!mp') in tournament manager chat (hidden by default)
SHOW_MP_COMMANDS=false

# Enables/disables the in-game overlay (!!!I AM NOT RESPONSIBLE FOR USING IT!!!).
ENABLE_INGAME_OVERLAY=false

# WARNING: EVERYTHING BELOW IS NOT TO BE TOUCHED UNNECESSARILY.

# Enables logs for tosu developers, not very intuitive for you, the end user.
# best not to include without developer's request.
DEBUG_LOG=false
OPEN_DASHBOARD_ON_STARTUP=true

# IP address where the websocket api server will be registered
# 127.0.0.1 = localhost
# 0.0.0.0.0 = all addresses
SERVER_IP=0.0.0.0
# The port on which the websocket api server will run
SERVER_PORT=24050
# The folder from which the overlays will be taken.
STATIC_FOLDER_PATH=./static
```

By the way, the annotation for SERVER IP in the default configuration file is also incorrect: “# 0.0.0.0.0=all addresses”, which should be 0.0.0.0

**Comment by cyperdark** [comment]
what exactly thf issue, besides different IP address

**Comment by wanjiaXG** [comment]
> what exactly thf issue, besides different IP address

There are 2 computers in the local area network
environment：
Computer A's IP: 192.168.6.200
Computer B's IP: 192.168.6.100
﻿
Computer A start osu! and tosu, configure files as described above.
﻿
Computer B as a live streaming machine, accessed tsou server，IP： 192.168.6.200
﻿
Appeared in the response HTML http://localhost and http://0.0.0.0 
This also means that computer B cannot access the web resources provided by computer A
So currently, tsou cannot work in a local area network and can only run as a standalone application

**Comment by wanjiaXG** [comment]
This issue should belong to a front-end bug,
After manual splicing URL, it can operate normally,
However, some plugins have 127.0.0.1:24050 written in the code, so some plugins cannot be used on the local area network

**Comment by cyperdark** [comment]
> HTML in the response appeared http://localhost/ and http://0.0.0.0/

will fix right now, but it doesnt mean counters wont work, they will work, unless counters have 127 in it, will fix it as well

**Comment by cyperdark** [comment]
@wanjiaXG try this build https://github.com/tosuapp/tosu/actions/runs/14153536921?pr=314
fixed ip address only

**Comment by wanjiaXG** [comment]
> [@wanjiaXG](https://github.com/wanjiaXG) try this build https://github.com/tosuapp/tosu/actions/runs/14153536921?pr=314 fixed ip address only

Still cant work, the required IP address is the IP address in the browser address bar, in my env, ip shound use 192.168.6.200, It shouldn't be 192.168.6.100, this is the client's address.

![Image](https://github.com/user-attachments/assets/3b759db5-743b-40b7-8d5f-4e57e5d6a639)

**Comment by wanjiaXG** [comment]
Or using relative URL links, I think it should be able to solve this preview iframe bug.
![Image](https://github.com/user-attachments/assets/0ac1c2a7-2796-40d3-8c54-b32530b03646)

**Comment by cyperdark** [comment]
try this build https://github.com/tosuapp/tosu/actions/runs/14153873097?pr=314

**Comment by wanjiaXG** [comment]
> try this build https://github.com/tosuapp/tosu/actions/runs/14153873097?pr=314

Cant work, still using the client's IP address

**Comment by cyperdark** [comment]
@wanjiaXG what about this one https://github.com/tosuapp/tosu/actions/runs/14154079699?pr=314

**Comment by cyperdark** [comment]
> now only plugins are left
they already updated, press update button on dashboard next to counter
